//! The `hunk-theme` mode: translate herdr's `[theme.custom]` palette into a
//! `hunk` custom theme so the review pane matches the rest of the switcher.
//!
//! `hunk` (the review viewer `bin/review.sh` launches) reads its own
//! `~/.config/hunk/config.toml`; a `theme = "custom"` plus a `[custom_theme]`
//! table of `#rrggbb` slots restyles it. We map both the **chrome** (background,
//! panels, border, accent, text, badge/file colours) **and the diff content area**
//! (context takes the panel background; add/remove rows a subtle tint of the accent
//! colours blended onto it) so the pane doesn't sit github-dark inside a herdr
//! panel. Only the syntax-token palette is left to the `base` theme. When the
//! plugin's `transparency` isn't disabled we also set `transparent_background`, so
//! the review matches the switcher's own translucency.
//!
//! **We never clobber a hand-written hunk config.** The file is written only when
//! it is absent or carries our marker line; a user who edits it (dropping the
//! marker) owns it from then on. With no `[theme.custom]` slots there is nothing to
//! translate, so nothing is written and hunk keeps its own default (`--theme auto`).

use std::fs;
use std::path::PathBuf;

use anyhow::Result;
use ratatui::style::Color;

use crate::data::{Config, Theme};

/// First line of a config we generated; its presence marks the file as ours to
/// rewrite. Editing the file out from under us is as simple as deleting this line.
const MARKER: &str = "# generated by herdr-ghq — delete this line to keep your own hunk theme";

/// `#rrggbb` for a slot colour. Only `Color::Rgb` occurs in a loaded theme (the
/// parser produces nothing else), so anything else yields `None` and is skipped.
fn hex(c: Color) -> Option<String> {
    match c {
        Color::Rgb(r, g, b) => Some(format!("#{r:02x}{g:02x}{b:02x}")),
        _ => None,
    }
}

/// Rough perceived luminance (0-255) of a slot, to pick a light vs. dark `base`.
fn luminance(c: Color) -> u16 {
    match c {
        Color::Rgb(r, g, b) => (r as u16 * 3 + g as u16 * 6 + b as u16) / 10,
        _ => 0,
    }
}

/// Mix `fg` `t` of the way toward it from `bg` (0.0 = bg, 1.0 = fg) as `#rrggbb`.
/// Used to tint the diff's add/remove backgrounds from the accent colours so they
/// sit on the herdr panel instead of the base theme's near-black.
fn blend(fg: Color, bg: Color, t: f32) -> Option<String> {
    match (fg, bg) {
        (Color::Rgb(fr, fgc, fb), Color::Rgb(br, bgc, bb)) => {
            let mix = |a: u8, b: u8| (a as f32 * t + b as f32 * (1.0 - t)).round() as u8;
            Some(format!(
                "#{:02x}{:02x}{:02x}",
                mix(fr, br),
                mix(fgc, bgc),
                mix(fb, bb)
            ))
        }
        _ => None,
    }
}

/// The `config.toml` text for a themed hunk, or `None` when the herdr theme has no
/// custom slots to translate (hunk then keeps its own default theme). `transparent`
/// lets the terminal (and herdr's translucent pane) show through hunk's surfaces, so
/// the review pane matches the switcher's own translucency.
pub fn render_config(theme: &Theme, transparent: bool) -> Option<String> {
    let mut rows: Vec<String> = Vec::new();
    // Direct herdr slot -> hunk [custom_theme] key. The chrome (window, panels,
    // border, accent, text) and the badge / file / note colours.
    const MAP: &[(&str, &str)] = &[
        ("panel_bg", "background"),
        ("surface0", "panel"),
        ("surface1", "panelAlt"),
        ("overlay0", "border"),
        ("accent", "accent"),
        ("overlay1", "accentMuted"),
        ("text", "text"),
        ("subtext0", "muted"),
        ("green", "badgeAdded"),
        ("red", "badgeRemoved"),
        ("subtext0", "badgeNeutral"),
        ("green", "fileNew"),
        ("red", "fileDeleted"),
        ("yellow", "fileRenamed"),
        ("blue", "fileModified"),
        ("subtext0", "fileUntracked"),
        ("green", "addedSignColor"),
        ("red", "removedSignColor"),
        ("subtext0", "lineNumberFg"),
        ("overlay0", "noteBorder"),
        ("surface0", "noteBackground"),
        ("surface1", "noteTitleBackground"),
        ("text", "noteTitleText"),
    ];
    for (slot, key) in MAP {
        if let Some(hexed) = theme.get(slot).and_then(hex) {
            rows.push(format!("{key} = \"{hexed}\""));
        }
    }

    // The diff *content* area: unless these are set too, hunk paints the code on its
    // base theme's near-black, which clashes with the herdr panel around it. Context
    // rows take the panel background; add/remove rows a subtle tint of the accent
    // colours blended onto it.
    if let Some(bg) = theme.get("panel_bg") {
        let bghex = hex(bg);
        let mut put = |key: &str, val: Option<String>| {
            if let Some(v) = val {
                rows.push(format!("{key} = \"{v}\""));
            }
        };
        put("contextBg", bghex.clone());
        put("contextContentBg", bghex.clone());
        put("lineNumberBg", bghex.clone());
        put("selectedHunk", theme.get("surface1").and_then(hex));
        put(
            "addedBg",
            theme.get("green").and_then(|c| blend(c, bg, 0.24)),
        );
        put(
            "addedContentBg",
            theme.get("green").and_then(|c| blend(c, bg, 0.15)),
        );
        put(
            "removedBg",
            theme.get("red").and_then(|c| blend(c, bg, 0.24)),
        );
        put(
            "removedContentBg",
            theme.get("red").and_then(|c| blend(c, bg, 0.15)),
        );
        put(
            "movedAddedBg",
            theme.get("blue").and_then(|c| blend(c, bg, 0.24)),
        );
        put(
            "movedRemovedBg",
            theme.get("mauve").and_then(|c| blend(c, bg, 0.24)),
        );
    }

    if rows.is_empty() {
        return None;
    }

    // A dark base for a dark background, a light base otherwise — this still drives
    // the syntax-highlighting palette; only the surfaces above are overridden.
    let base = match theme.get("panel_bg").map(luminance) {
        Some(l) if l >= 128 => "github-light-default",
        _ => "github-dark-default",
    };

    let mut out = String::new();
    out.push_str(MARKER);
    out.push('\n');
    out.push_str("theme = \"custom\"\n");
    out.push_str(&format!(
        "transparent_background = {}\n\n",
        if transparent { "true" } else { "false" }
    ));
    out.push_str("[custom_theme]\n");
    out.push_str(&format!("base = \"{base}\"\n"));
    out.push_str("label = \"herdr\"\n");
    for row in rows {
        out.push_str(&row);
        out.push('\n');
    }
    Some(out)
}

/// `~/.config/hunk/config.toml`, honouring `XDG_CONFIG_HOME`.
fn config_path() -> PathBuf {
    let base = std::env::var("XDG_CONFIG_HOME")
        .unwrap_or_else(|_| format!("{}/.config", std::env::var("HOME").unwrap_or_default()));
    PathBuf::from(base).join("hunk").join("config.toml")
}

/// True when we may write `path`: it does not exist, or it is one we generated
/// (carries [`MARKER`]). A user-authored config is never overwritten.
fn ours(path: &PathBuf) -> bool {
    match fs::read_to_string(path) {
        Ok(text) => text.starts_with(MARKER),
        Err(_) => true, // absent (or unreadable): safe to create
    }
}

/// Write the themed hunk config when there is a palette to translate and the file
/// is ours to write. Any failure is non-fatal — hunk simply uses its own theme.
pub fn ensure_theme() -> Result<()> {
    // Match the switcher's own translucency: transparent unless the plugin's
    // `transparency` setting is explicitly disabled.
    let transparent = Config::load().get("transparency", "auto") != "disabled";
    let Some(text) = render_config(&Theme::load(), transparent) else {
        return Ok(());
    };
    let path = config_path();
    if !ours(&path) {
        return Ok(());
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, text)?;
    fs::rename(&tmp, &path)?;
    Ok(())
}

/// `herdr-ghq-switcher hunk-theme` — regenerate the themed hunk config. Called by
/// `bin/review.sh` before it launches hunk. Best-effort: prints nothing on success.
pub fn main() -> Result<()> {
    ensure_theme()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_slots_writes_nothing() {
        assert!(render_config(&Theme::default(), true).is_none());
    }

    #[test]
    fn a_palette_becomes_a_custom_theme_with_mapped_chrome_and_content() {
        let theme = Theme::from_slots(&[
            ("panel_bg", "#101014"),
            ("accent", "#89b4fa"),
            ("text", "#cdd6f4"),
            ("green", "#a6e3a1"),
        ]);
        let cfg = render_config(&theme, true).unwrap();
        assert!(cfg.starts_with(MARKER), "{cfg}");
        assert!(cfg.contains("theme = \"custom\""), "{cfg}");
        assert!(cfg.contains("transparent_background = true"), "{cfg}");
        assert!(cfg.contains("[custom_theme]"), "{cfg}");
        // A dark background picks the dark base.
        assert!(cfg.contains("base = \"github-dark-default\""), "{cfg}");
        // Chrome slots map to their hunk keys, lower-cased hex.
        assert!(cfg.contains("background = \"#101014\""), "{cfg}");
        assert!(cfg.contains("accent = \"#89b4fa\""), "{cfg}");
        assert!(cfg.contains("badgeAdded = \"#a6e3a1\""), "{cfg}");
        // The diff content area is themed too: context takes the panel bg, and the
        // added rows a green tint blended onto it (not the base theme's near-black).
        assert!(cfg.contains("contextBg = \"#101014\""), "{cfg}");
        assert!(cfg.contains("addedContentBg = \"#"), "{cfg}");
        // A slot with no colour (red) leaves its keys out entirely.
        assert!(!cfg.contains("badgeRemoved"), "{cfg}");
        assert!(!cfg.contains("removedContentBg"), "{cfg}");
    }

    #[test]
    fn transparency_can_be_turned_off() {
        let theme = Theme::from_slots(&[("panel_bg", "#101014"), ("text", "#cdd6f4")]);
        let cfg = render_config(&theme, false).unwrap();
        assert!(cfg.contains("transparent_background = false"), "{cfg}");
    }

    #[test]
    fn a_light_background_picks_the_light_base() {
        let theme = Theme::from_slots(&[("panel_bg", "#eff1f5"), ("text", "#4c4f69")]);
        let cfg = render_config(&theme, true).unwrap();
        assert!(cfg.contains("base = \"github-light-default\""), "{cfg}");
    }
}
